CP-1586: Resync vswitch patch to base 1571:9a920e075e14 (git 366d78fd926e3d7f2b78ec8cf63dbab72fa9c8b7)
HG commit id: 96a49e1f90d06618c6bd01089c06ab7f955de231

diff --git a/master/xenserver-correct-status-when-not-in-vswitch-mode.patch b/master/xenserver-correct-status-when-not-in-vswitch-mode.patch
--- a/master/xenserver-correct-status-when-not-in-vswitch-mode.patch
+++ b/master/xenserver-correct-status-when-not-in-vswitch-mode.patch
@@ -1,16 +1,16 @@
-diff -r a779af6fe2db xenserver/etc_init.d_openvswitch
---- a/xenserver/etc_init.d_openvswitch	Mon Jun 14 11:36:53 2010 +0100
-+++ b/xenserver/etc_init.d_openvswitch	Mon Jun 14 11:41:16 2010 +0100
-@@ -27,7 +27,11 @@
- NETWORK_MODE=$(cat /etc/xensource/network.conf)
- if test "$NETWORK_MODE" = bridge; then
-     echo "Open vSwitch disabled (/etc/xensource/network.conf is 'bridge')" >&2
--    exit 0
-+    if [ "$1" = "status" ] ; then
-+	exit 1
-+    else
-+	exit 0
-+    fi
- fi
- 
- # General config variables in /etc/sysconfig/openvswitch
+diff -r 9a920e075e14 xenserver/etc_init.d_openvswitch
+--- a/xenserver/etc_init.d_openvswitch	Mon Jun 28 14:14:08 2010 -0700
++++ b/xenserver/etc_init.d_openvswitch	Wed Jun 30 12:05:56 2010 +0100
+@@ -29,7 +29,11 @@
+     vswitch|openvswitch)
+         ;;
+     bridge)
+-        exit 0
++        if [ "$1" = "status" ] ; then
++           exit 1
++        else
++           exit 0
++        fi
+         ;;
+     *)
+         echo "Open vSwitch disabled (/etc/xensource/network.conf is invalid)" >&2
